### ISSUE TITLE
TabbyPresentationSnippet price requires final value so I can not assent variable to it 

### ISSUE THREAD

**Issue by ismail4947** [tabby-ai/tabby_flutter_inapp_sdk#19]
child: TabbyPresentationSnippet(
                                              price: 100.00,  // this can not be variable like cart_price
                                              currency: Currency.sar,
                                              lang: Lang.ar,
                                            ),

**Comment by kuznetsov-from-wonderland** [comment]
It actually could be variable that is `final`. We've never been reported that our other clients ever faced such issue. The way for you to resolve this issue is to slightly refactor your code. And if you need any help or assistance - please contact Tabby integrations team and they will provide any necessary support.
